### ISSUE TITLE
可能出现文章评论区共用一个issue

### ISSUE THREAD

**Issue by fengwei2002** [JoeyBling/vuepress-plugin-mygitalk#1]
当我的vuepress每个文章文件夹下都存在一个README.md时

若为其中任意一个README.md进行初始化issue且同时进行评论，

那么其他文件夹下的README.md 并不会去新建一个属于自己的 issue

而是使用第一个 README.md 文章 初始化的 issue

而其他文章就不出现这个问题

[我的博文目录参考](https://github.com/fengwei2002/vuepress_final)

[我的vuepress网站](https://feng-w.cn/)

这是bug吗？

**Comment by JoeyBling** [comment]
@fengwei2002 博客有点卡，好像没看到你使用了此插件

**Comment by JoeyBling** [comment]
@fengwei2002 有具体体现的文章吗？我试了没问题啊

**Comment by fengwei2002** [comment]
可能是页面没刷新的问题？又能用了...

**Comment by JoeyBling** [comment]
@fengwei2002 好的，有问题留言即可，看到马上解决
